//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syllabus.Resource {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locatization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locatization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syllabus.Resource.Locatization", typeof(Locatization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Uygulama/Lab (saat/hafta) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yardımcı(ları) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıktı Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button_export {
            get {
                return ResourceManager.GetString("button_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button_import {
            get {
                return ResourceManager.GetString("button_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Ders Kaydı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML Yükleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button2 {
            get {
                return ResourceManager.GetString("button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button3 {
            get {
                return ResourceManager.GetString("button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yardım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button4 {
            get {
                return ResourceManager.GetString("button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string buttun_save {
            get {
                return ResourceManager.GetString("buttun_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yenile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string buttun_save_main {
            get {
                return ResourceManager.GetString("buttun_save_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katkı Düzeyi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Contribution_Level {
            get {
                return ResourceManager.GetString("Contribution_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dersin Koordinatörü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Coordinator {
            get {
                return ResourceManager.GetString("Coordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temel Ders benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CoreCourses {
            get {
                return ResourceManager.GetString("CoreCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dersin Kategorisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CourseCategory {
            get {
                return ResourceManager.GetString("CourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yerel Kredi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders Tanımı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süre (Saat) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AKTS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ECTS {
            get {
                return ResourceManager.GetString("ECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arazi Çalışması benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Field_Work {
            get {
                return ResourceManager.GetString("Field_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arazi Çalışması benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FieldWork {
            get {
                return ResourceManager.GetString("FieldWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final Sınavı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Final_Exam {
            get {
                return ResourceManager.GetString("Final_Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final Sınavı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FinalExam {
            get {
                return ResourceManager.GetString("FinalExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sllyabus Programı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string form_Main {
            get {
                return ResourceManager.GetString("form_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ödev benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Homework_Assignments {
            get {
                return ResourceManager.GetString("Homework_Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ödev benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Homework_Assignmentss {
            get {
                return ResourceManager.GetString("Homework_Assignmentss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label_Code {
            get {
                return ResourceManager.GetString("label_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label_Lesson {
            get {
                return ResourceManager.GetString("label_Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label_Lessonss {
            get {
                return ResourceManager.GetString("label_Lessonss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sisteme Kayıtlı Dersler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Laboratuvar / Uygulama Ders Saati benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Laboratory_Application_Hours {
            get {
                return ResourceManager.GetString("Laboratory_Application_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Laboratuvar / Uygulama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Laboratory_Applicationxtbooks {
            get {
                return ResourceManager.GetString("Laboratory_Applicationxtbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dersin Dili benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Öğretim Eleman(lar)ı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lecturer {
            get {
                return ResourceManager.GetString("Lecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dersin Düzeyi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uzmanlık/Alan Dersleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MajorAreaCourses {
            get {
                return ResourceManager.GetString("MajorAreaCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Önerilen Okumalar/Materyaller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim ve Yönetim Becerileri Dersleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MediaandManagementSkillsCourses {
            get {
                return ResourceManager.GetString("MediaandManagementSkillsCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara Sınav benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Midterm {
            get {
                return ResourceManager.GetString("Midterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara Sınavlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Midtermss {
            get {
                return ResourceManager.GetString("Midtermss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Numberr {
            get {
                return ResourceManager.GetString("Numberr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dersin Amacı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sözlü Sınav benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Oral_Exam {
            get {
                return ResourceManager.GetString("Oral_Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sözlü Sınav benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OralExams {
            get {
                return ResourceManager.GetString("OralExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Öğrenme Çıktıları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Outcomes {
            get {
                return ResourceManager.GetString("Outcomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katılım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Participation {
            get {
                return ResourceManager.GetString("Participation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ön-Koşul(lar) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Prerequisites {
            get {
                return ResourceManager.GetString("Prerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunum / Jüri Önünde Sunum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Presentation_Jury {
            get {
                return ResourceManager.GetString("Presentation_Jury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunum / Jüri Önünde Sunum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Presentation_Juryy {
            get {
                return ResourceManager.GetString("Presentation_Juryy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program Yeterlilikleri / Çıktıları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Program_Competencies_Outcomes {
            get {
                return ResourceManager.GetString("Program_Competencies_Outcomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proje benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proje benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Projectt {
            get {
                return ResourceManager.GetString("Projectt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Küçük Sınav / Stüdyo Kritiği benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Quizzes_Studio_Critiques {
            get {
                return ResourceManager.GetString("Quizzes_Studio_Critiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Küçük Sınav / Stüdyo Kritiği benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Quizzes_StudioCritiques {
            get {
                return ResourceManager.GetString("Quizzes_StudioCritiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ön Hazırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RelatedPreparation {
            get {
                return ResourceManager.GetString("RelatedPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yarıyıl benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yarıyıl Aktiviteleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SemesterActivities {
            get {
                return ResourceManager.GetString("SemesterActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yarıyıl Aktiviteleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SemesterActivitiess {
            get {
                return ResourceManager.GetString("SemesterActivitiess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seminer/Çalıştay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Seminar_Workshop {
            get {
                return ResourceManager.GetString("Seminar_Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seminer/Çalıştay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Seminar_Workshopp {
            get {
                return ResourceManager.GetString("Seminar_Workshopp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dersin Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sLessonName {
            get {
                return ResourceManager.GetString("sLessonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sınıf Dışı Ders Çalışması benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Study_Hours_Out_of_Class {
            get {
                return ResourceManager.GetString("Study_Hours_Out_of_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konular benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destek Dersleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SupportiveCourses {
            get {
                return ResourceManager.GetString("SupportiveCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ders Kitabı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Textbooks {
            get {
                return ResourceManager.GetString("Textbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teorik Ders Saati benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TheoreticalCourseHours {
            get {
                return ResourceManager.GetString("TheoreticalCourseHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teori (saat/hafta) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Theory {
            get {
                return ResourceManager.GetString("Theory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aktarılabilir Beceri Dersleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TransferableSkillCourses {
            get {
                return ResourceManager.GetString("TransferableSkillCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dersin Türü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hafta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katkı Payı % benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Weigthing {
            get {
                return ResourceManager.GetString("Weigthing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İş Yükü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Workload {
            get {
                return ResourceManager.GetString("Workload", resourceCulture);
            }
        }
    }
}
